import {
  DashboardOutlined,
  EnvironmentOutlined,
  SafetyOutlined,
  RedEnvelopeOutlined,
  ShoppingCartOutlined,
  CreditCardOutlined,
  ShoppingOutlined,
  UserOutlined,
  TableOutlined,
  FormOutlined,
  AreaChartOutlined,
  FileSearchOutlined,
} from '@ant-design/icons-vue';

export const adminMenus = [
  {
    key: 'Home',
    label: '控制台',
    routeName: 'Home',
    path: '',
    icon: DashboardOutlined,
    affix: true,
    component: () => import('@/views/home/HomeView.vue'),
  },
  {
    key: 'User',
    label: '用户管理',
    routeName: 'UserManagement',
    path: 'users',
    icon: UserOutlined,
    component: () => import('@/views/user/UserManagement.vue'),
  },
  {
    key: 'Address',
    label: '地址管理',
    routeName: 'AddressManagement',
    path: 'addresses',
    icon: EnvironmentOutlined,
    component: () => import('@/views/address/AddressManagement.vue'),
  },
  {
    key: 'AdminAuth',
    label: '权限管理',
    icon: SafetyOutlined,
    path: 'admin-auth',
    children: [
      {
        key: 'RoleManagement',
        label: '角色管理',
        routeName: 'RoleManagement',
        path: 'admin-auth/roles',
        component: () => import('@/views/admin-auth/RoleManagement.vue'),
      },
      {
        key: 'PermissionAssignment',
        label: '权限分配',
        routeName: 'PermissionAssignment',
        path: 'admin-auth/permissions',
        component: () => import('@/views/admin-auth/PermissionAssignment.vue'),
      },
      {
        key: 'AdminUser',
        label: '管理员列表',
        routeName: 'AdminUserManagement',
        path: 'admin-auth/users',
        component: () => import('@/views/admin-user/AdminUserManagement.vue'),
      },
    ],
  },
  {
    key: 'Coupon',
    label: '优惠券管理',
    routeName: 'CouponManagement',
    path: 'coupons',
    icon: RedEnvelopeOutlined,
    component: () => import('@/views/coupon/CouponManagement.vue'),
  },
  {
    key: 'Order',
    label: '订单管理',
    path: 'orders',
    icon: ShoppingCartOutlined,
    children: [
      {
        key: 'OrderList',
        label: '订单列表',
        routeName: 'OrderList',
        path: 'orders/list',
        component: () => import('@/views/order/OrderList.vue'),
      },
      {
        key: 'Deposit',
        label: '用户押金',
        routeName: 'DepositManagement',
        path: 'deposits',
        component: () => import('@/views/deposit/DepositManagement.vue'),
      },
      {
        key: 'OrderAfterSale',
        label: '订单售后',
        routeName: 'OrderAfterSale',
        path: 'orders/after-sale',
        component: () => import('@/views/order/OrderAfterSale.vue'),
      },
    ],
  },
  {
    key: 'Payment',
    label: '支付管理',
    routeName: 'PaymentManagement',
    path: 'payments',
    icon: CreditCardOutlined,
    component: () => import('@/views/payment/PaymentManagement.vue'),
  },
  {
    key: 'Product',
    label: '商品管理',
    icon: ShoppingOutlined,
    path: 'products',
    children: [
      {
        key: 'ProductList',
        label: '商品列表',
        routeName: 'ProductList',
        path: 'products/list',
        component: () => import('@/views/product/ProductList.vue'),
      },
      {
        key: 'ProductCategory',
        label: '商品分类',
        routeName: 'ProductCategory',
        path: 'products/categories',
        component: () => import('@/views/product/ProductCategory.vue'),
      },
    ],
  },
  {
    key: 'DataAnalysis',
    label: '数据分析',
    routeName: 'DataAnalysis',
    path: 'data-analysis',
    icon: AreaChartOutlined,
    component: () => import('@/views/analysis/DataAnalysis.vue'),
  },
  {
    key: 'SystemLogs',
    label: '系统日志',
    routeName: 'SystemLogs',
    path: 'system-logs',
    icon: FileSearchOutlined,
    component: () => import('@/views/system/SystemLogs.vue'),
  },
  {
    key: 'TableDemo',
    label: '通用表格示例',
    routeName: 'GeneralTableDemo',
    path: 'table-demo',
    icon: TableOutlined,
    component: () => import('@/views/table/GeneralTableDemo.vue'),
  },
  {
    key: 'FormDemo',
    label: '通用表单示例',
    routeName: 'GeneralFormDemo',
    path: 'form-demo',
    icon: FormOutlined,
    component: () => import('@/views/form/GeneralFormDemo.vue'),
  },
];
